FILTER_TYPES = {
  "Badbunny": "Life",
  "Tuileries": "Life",
  "Sardinia": "Life",
  "Berlin": "Life",
  "Dolce": "Life",
  "Humble": "Life",
  "Clear": "Life",
  "Vibrant II": "Life",
  "Vibrant I": "Life",
  "Copper": "Life",
  "Plum": "Life",
  "Urbanoid": "Life",
  "Life I": "Life",
  "Life II": "Life",
  "Robust": "Life",
  "Salt": "Life",
  "Metal": "Life",
  "Gray": "Life",
  "Shadow": "Life",
  "Milky Green": "Life",
  "Taro": "Life",
  "Red Tea": "Life",
  "Mistletoe": "Life",
  "Jingle Bells": "Life",
  "Conifer Cone": "Life",
  "Pine": "Life",
  "Gingerbread": "Life",
  "Nature": "Life",
  "Autumn": "Life",
  "Cold": "Life",
  "Tan": "Life",
  "Umber": "Life",
  "Holiday": "Life",
  "Gourmet I": "Food",
  "Gourmet II": "Food",
  "Candy Cane": "Food",
  "Snack": "Food",
  "French": "Food",
  "Bake": "Food",
  "Cuisine": "Food",
  "Western": "Food",
  "Eclipse": "Food",
  "White Tea": "Food",
  "Peach": "Food",
  "Cold brew": "Food",
  "Latte": "Food",
  "Late-night diner": "Food",
  "Veggie": "Food",
  "Comfort food": "Food",
  "Fling": "Movies",
  "Hope": "Movies",
  "Freedom": "Movies",
  "Barbie": "Movies",
  "Oppenheimer": "Movies",
  "Budapest": "Movies",
  "Dispatch": "Movies",
  "Black Panther": "Movies",
  "Dont Look Up": "Movies",
  "Flipped": "Movies",
  "High Saturation": "Movies",
  "Green Orange": "Movies",
  "Blue Grey": "Movies",
  "Dark Brown": "Movies",
  "Green Yellow": "Movies",
  "Scent": "Movies",
  "Inception": "Movies",
  "One Day": "Movies",
  "Oasis": "Movies",
  "Dunkirk": "Movies",
  "Winter Snow": "Movies",
  "Love letter": "Movies",
  "Ocean Road": "Movies",
  "Woodland": "Movies",
  "Maple": "Movies",
  "Nighty Night": "Night Scene",
  "Warm Natural": "Night Scene",
  "Orange Blue": "Night Scene",
  "Greenish Grey": "Night Scene",
  "Cold Blue": "Night Scene",
  "Radiance": "Scenery",
  "Las Vegas": "Scenery",
  "Hawaii": "Scenery",
  "San Francisco": "Scenery",
  "Voyage": "Scenery",
  "Clear ll": "Scenery",
  "Maldives": "Scenery",
  "Hiking": "Scenery",
  "Green Lake": "Scenery",
  "Gold Coast": "Scenery",
  "Dark Brown": "Scenery",
  "Nightfall": "Scenery",
  "Garden": "Scenery",
  "Ice City": "Scenery",
  "December": "Scenery",
  "Clear": "Scenery",
  "Picnic": "Scenery",
  "Dusk": "Scenery",
  "Hasselblad": "Scenery",
  "Fuji": "Scenery",
  "Shade": "Scenery",
  "Remote": "Scenery",
  "Spring Chorus": "Scenery",
  "Light Green": "Scenery",
  "Oshima Cherry": "Scenery",
  "Provia 100": "Retro",
  "Agfa 400": "Retro",
  "Gold 200": "Retro",
  "Retro IV": "Retro",
  "Retro I": "Retro",
  "Retro II": "Retro",
  "Retro III": "Retro",
  "Friends": "Retro",
  "Miami": "Retro",
  "Beverly": "Retro",
  "Princeton": "Retro",
  "Photo Booth": "Retro",
  "VHS I": "Retro",
  "VHS II": "Retro",
  "VHS III": "Retro",
  "Film": "Retro",
  "1980": "Retro",
  "Roman Holiday": "Mono",
  "Tunnel": "Mono",
  "Fade": "Mono",
  "Black Forest": "Mono",
  "Warlock": "Mono",
  "Jazz": "Mono",
  "Brown": "Mono",
  "BW 1": "Mono",
  "BW 2": "Mono",
  "BW 3": "Mono",
  "Weird": "Style",
  "Yandere": "Style",
  "Negative": "Style",
  "Night Vision": "Style",
  "Dope": "Style",
  "Sunset": "Style",
  "Burgundy": "Style",
  "Lost forest": "Style",
  "Secluded blue": "Style",
  "Purple Limbo": "Style",
  "Ghost": "Style",
  "Pumpkin": "Style",
  "Red Devil": "Style",
  "Blue Devil": "Style",
  "Vaporwave": "Style",
  "Cyber light": "Style",
  "Sepia": "Style",
  "Red": "Style"
}
