import random

BASIC_INTENSITY_VALUE=random.randint(70, 90)
BASIC_COLOR_ADJUSTMENT_COLOR_SATURATION=random.randrange(-7, 15)
BASIC_COLOR_ADJUSTMENT_COLOR_TEMPERATURE=random.randrange(-7, 15)
BASIC_COLOR_ADJUSTMENT_LIGHTNESS_BRIGHTNESS=random.randrange(-5, 25)
BASIC_COLOR_ADJUSTMENT_LIGHTNESS_CONTRAST=random.randrange(-6, 20)
BASIC_COLOR_ADJUSTMENT_LIGHTNESS_SHINE=random.randrange(-7, 15)
BASIC_COLOR_ADJUSTMENT_LIGHTNESS_HIGHLIGHT=random.randrange(-8, 30)
BASIC_COLOR_ADJUSTMENT_LIGHTNESS_SHADOW=random.randrange(-5, 25)

BASIC_BLEND_OPACITY=random.randrange(95, 100)
BASIC_TRANSFORM_SCALE=random.randrange(70, 100)
BASIC_TRANSFORM_POSITION_X=random.randrange(-7, 7)
BASIC_TRANSFORM_POSITION_Y=random.randrange(-7, 7)
BASIC_TRANSFORM_ROTATE=random.randrange(-3, 3)

BASIC_EFFECT_SHARPNESS=random.randrange(0, 100)
BASIC_EFFECT_VIGNETTE=random.randrange(-10, 15)
BASIC_EFFECT_FADE=random.randrange(0, 50)
BASIC_EFFECT_GRAIN=random.randrange(0, 50)

SMART_TOOLS_RETOUCH_BODY_SLIM=random.randrange(0, 100)
SMART_TOOLS_RETOUCH_BODY_LEGS=random.randrange(0, 100)
SMART_TOOLS_RETOUCH_BODY_WAIST=random.randrange(0, 100)
SMART_TOOLS_RETOUCH_BODY_HEAD=random.randrange(0, 100)
SMART_TOOLS_RETOUCH_BODY_SMOOTH=random.randrange(0, 100)
SMART_TOOLS_RETOUCH_BODY_BRIGHTEN=random.randrange(0, 100)

PERCENTAGE_OF_VIDEO_CUT = random.randrange(5, 12)